"""added users table

Revision ID: 363e0ec24560
Revises: 
Create Date: 2023-09-06 16:11:22.973537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363e0ec24560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_Name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True, max_length=254),
    sa.Column('first_Name', sa.String(), nullable=True),
    sa.Column('last_Name', sa.String(), nullable=True),
    sa.Column('phone_Number', sa.Integer(), nullable=True, max_length=30),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKey('buyer.id', name='buyer_fk')
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
