"""Added buyers and sellers tables

Revision ID: c913bd3301d9
Revises: eb606623cd1e
Create Date: 2023-09-07 09:24:40.836703

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c913bd3301d9'
down_revision = 'eb606623cd1e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('users', ['email'])

    with op.batch_alter_table('buyers') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_buyers_seller_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_buyers_buyer_id_users', type_='foreignkey')
        batch_op.create_foreign_key(
            op.f('fk_buyers_user_id_users'),
            'users',
            ['user_id'],
            ['id']
        )
        batch_op.drop_column('seller_id')
        batch_op.drop_column('buyer_id')

    op.create_table('sellers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sellers_user_id_users')),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('user_Name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_Name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_Name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_Number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, 'users', ['email'])

    with op.batch_alter_table('buyers') as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_buyers_buyer_id_users', 'users', ['buyer_id'], ['id'])
        batch_op.create_foreign_key('fk_buyers_seller_id_users', 'users', ['seller_id'], ['id'])
        batch_op.drop_column('user_id')

    op.drop_table('sellers')
    # ### end Alembic commands ###
