"""added buyers table

Revision ID: e4443c9b3224
Revises: eb606623cd1e
Create Date: 2023-09-06 19:21:41.425973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4443c9b3224'
down_revision = 'eb606623cd1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_buyers_buyer_id_users')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_buyers_seller_id_users')),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True  # Add this line to check if the table already exists
    )
    # ...

    op.add_column('users', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'first_Name')
    op.drop_column('users', 'user_Name')
    op.drop_column('users', 'last_Name')
    op.drop_column('users', 'phone_Number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_Number', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('last_Name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('user_Name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('first_Name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'user_name')
    op.drop_table('buyers')
    # ### end Alembic commands ###
"""added buyers table

Revision ID: e4443c9b3224
Revises: eb606623cd1e
Create Date: 2023-09-06 19:21:41.425973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4443c9b3224'
down_revision = 'eb606623cd1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_buyers_buyer_id_users')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_buyers_seller_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'first_Name')
    op.drop_column('users', 'user_Name')
    op.drop_column('users', 'last_Name')
    op.drop_column('users', 'phone_Number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_Number', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('last_Name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('user_Name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('first_Name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'user_name')
    op.drop_table('buyers')
    # ### end Alembic commands ###
