"""fix users table

Revision ID: eb606623cd1e
Revises: 363e0ec24560
Create Date: 2023-09-06 16:14:23.965838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb606623cd1e'
down_revision = '363e0ec24560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
